### DISCUSSION TITLE
Does it make sense to have default OIDC information

### DISCUSSION THREAD

**Discussion by CannonLock** [PelicanPlatform/pelican#2312] [Ideas]
Well creating the new OIDC flow I have noticed there are defaults that seem very unique to the CHTC. 

Most notably:
```
OIDC:
  Issuer: "https://cilogon.org"
  AuthorizationEndpoint: "https://cilogon.org/authorize"
  DeviceAuthEndpoint: "https://cilogon.org/oauth2/device_authorization"
  TokenEndpoint: "https://cilogon.org/oauth2/token"
  UserInfoEndpoint: "https://cilogon.org/oauth2/userinfo"
```

Does it really make sense to have these as defaults?

My main issue with them is when guiding users through a flow to set these values gets tricky when there are defaults that I am guessing are not so likely they are reasonable to assume.

Since these values have to be considered and chosen carefully no matter what I don't think it makes sense to have defaults for them.
