### ISSUE TITLE
Consolidate configuration option hierarchies

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#130]
We should make the options configurable via `pelican.yaml` more consistent and hierarchical. For example, there's an option `Director.DefaultResponse` that is clearly an option to configure behavior for a director instance. Elsewhere, we have options that configure the director like "MaxMindKeyFile" and "GeoIPLocation", but it's not immediately obvious from the name what service(s) these affect. I think we should make these types of configurations hierarchical so that we wind up with a config more like:
```
Director:
    DefaultResponse: cache
    MaxMindKeyFile: /path/to/kf
    GeoIPLocation: /path/to/location
```
