### ISSUE TITLE
Incorrect Descriptions and Minor Typos in docs/parameters.yaml

### ISSUE THREAD

**Issue by Saartank** [PelicanPlatform/pelican#1667]
Some parameters in `docs/parameters.yaml` have incorrect descriptions:

```yaml
---
name: Origin.ScitokensRestrictedPaths
description: |+
  Enable the built-in issuer daemon for the origin.
type: stringSlice
default: none
components: ["origin"]
---
name: Origin.ScitokensMapSubject
description: |+
  Enable the built-in issuer daemon for the origin.
type: bool
default: false
components: ["origin"]
---
name: Origin.ScitokensDefaultUser
description: |+
  Enable the built-in issuer daemon for the origin.
type: string
default: none
components: ["origin"]
---
name: Origin.ScitokensUsernameClaim
description: |+
  Enable the built-in issuer daemon for the origin.
type: string
default: none
components: ["origin"]
---
name: Origin.ScitokensNameMapFile
description: |+
  Enable the built-in issuer daemon for the origin.
type: string
default: none
components: ["origin"]
```

These parameters all incorrectly share the description of `Origin.EnableIssuer`.

Also, there are minor typos in some descriptions, for example in the description below the phrase "all headers and requests" should appear before the list of accepted values.

```yaml
---
name: Logging.Origin.Http
description: |+
  Logging level for the HTTP component of the origin. Increasing to debug will cause the Xrootd daemon to log.
  Accepted values: `trace`, `debug`, `info`, `warn`, `error`, `fatal`, `panic`
  all headers and requests.
type: string
default: error
components: ["origin"]
---
```
