### ISSUE TITLE
`Issuer.GroupRequirements` does not enforce the listed groups

### ISSUE THREAD

**Issue by brianaydemir** [PelicanPlatform/pelican#1701]
Pelican Version: hub.opensciencegrid.org/pelican_platform/osdf-origin:v7.10.11

Pelican Service:
- [x] Origin

**Describe the bug**
When enabling the origin's built-in OA4MP token issuer, it will issue tokens to authenticated identities that contain none of the groups listed in the `Issuer.GroupRequirements` setting.

**To Reproduce**
1. Configure an origin with at least
```
Origin:                                                                         
  EnableIssuer: true
Issuer:                                                                         
  GroupRequirements: ["some_group_1"]
```

2. Use `pelican object share` to get a sharing URL for some object served by the origin.
3. Authenticate with an identity that isn't a member of `some_group_1`.
4. Observe that you're still given a sharing URL containing a valid token.

**Expected behavior**
`Issuer.GroupRequirements` should behave as [documented](https://docs.pelicanplatform.org/parameters#Issuer-GroupRequirements): "A request must be mapped to one of the groups in this list to successfully authenticate."
