### ISSUE TITLE
Configuration Docs page has non-functional example yaml

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#1804]
Our [config parameters docs page](https://docs.pelicanplatform.org/parameters) starts out boldly with an example YAML config file, and we've observed users trying to copy-paste the example as a template for configuring their service.

Unfortunately, the example yaml is gobbledygook that doesn't doesn't compile, let alone work as a functional template...

At minimum, we should provide a config template that compiles. The best case would be to provide a minimal config example for each component -- it _may_ be possible to provide one big config template that acts as a minimal working example for _all_ components, but that might be more confusing than helpful. @aowen-uwmad, what do you think is ideal here? I'm inclined to think we create one minimal config per component.

**Comment by jhiemstrawisc** [comment]
In discussion with @aowen-uwmad, and we think a minimal config per component is good, but we'd also like to link out to `osg-htc.org` where we can host an example for each service of "how we do things in production"

**Comment by CannonLock** [comment]
What is the goal of a minimal config?

The best config is the default values, so our minimal config would be the default values. Depending on how dynamic the default values are this might cause pain if we change the default values without updating this minimal config.

**Comment by jhiemstrawisc** [comment]
There are some defaults that can't be filled in for generic cases, e.g. if you're setting up an origin, you still need to define the origin's exports, capabilities, federation discovery url, etc. I think most of our services can be set up as bare bones in ~15-20 lines of config. My goal is that someone could copy-paste, fill in a few blanks, and then run the service without any crashes/errors.

**Comment by CannonLock** [comment]
Ah makes sense, so this won't compile but it will be closer to compiling.

**Comment by brianaydemir** [comment]
I propose the following, just to put forth something concrete and valid (if not useful-on-its-own):

```
## Tell Pelican whom to contact for the federation's configuration.
Federation:
  DiscoveryUrl: https://federation-director.example.org:8444

## Ignore errors with TLS certificates, which is helpful during testing.
TLSSkipVerify: true

## Configure our origin to export a directory on the host's filesystem.
Origin:
  StorageType: posix
  Exports:
    - StoragePrefix: /pelican-origin/namespace/testing
      FederationPrefix: /testing
      Capabilities: ["PublicReads", "Writes", "Listings", "DirectReads"]
```

(As an aside, let this be a reason [to consider TOML](https://toml.io/), not least of all because it has a more helpful web presence.)
