### ISSUE TITLE
Published dev containers should only track main, but they also track tags

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#1945]
@Saartank and I were scratching our heads over why some recent  images tagged `pelican-dev:latest-itb` didn't have the expected dependencies (xrootd-purge, in particular) even though the Dockerfile changes that installed them were merged last week.

As it turns out, I think the issue is in the action that builds+releases our dev containers, which has the following trigger definition:
```
on:
  pull_request:
  push:
    tags:
      # only build and publish container on v7.0.0 and up
      - v[7-9]\.[0-9]+\.[0-9]+-**
      - v[1-9][0-9]+\.[0-9]+\.[0-9]+-**
    branches:
      - main
```

This, combined with a bit of sleuthing, and I realized that the 7.11/7.12 patches Emma and I published _also_ generated containers tagged `latest-itb`, although they did so using the source code as it exists for those patches -- in other words, without the Dockerfile changes. I believe that when @Saartank and I were testing, we both happened to end up with containers that weren't built from main, but from some other branch.

I think this is probably a mistake and that our dev containers should only track changes in main, or at the very least dev containers published from a tag should not assume the `latest-itb` tag.
