### ISSUE TITLE
Move `Transport.*` configuration options into the docs for `param` generation

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#213]
One of the final sets of configuration variables we should move into `parameters.yaml` is the set of `Transport.*` options. My vote is that these remain a top-level configuration option, resulting in a config that looks like:
```
Transport:
    DialerTimeout: 10s
    DialerKeepAlive: 30s
    MaxIdleConns: 30
    ....
```
