### ISSUE TITLE
Modify Director to make IP ranges pinnable to a specific cache 

### ISSUE THREAD

**Issue by jhiemstrawisc** [PelicanPlatform/pelican#397]
In some instances, we may need to say that an IP range like 10.0.0.0/8 should be pinned to a particular cache, or perhaps a certain lat/long. Of course, we should also make this work with IPv6, although I'm not sure what support we have internally for IPv6 at the moment.

This should be configurable within the director, such that something like (note I haven't given naming much thought yet)
```
Director:
    KnownIPs:
        - IP: "10.0.0.0/8"
        cache: "cache-name"
        - IP: "128.104.123.234"
        cache: "different-cache"
```
will cause those IP addresses to use the specified caches.
