### ISSUE TITLE
osdf binary should respect 'PELICAN_*' env vars

### ISSUE THREAD

**Issue by brianhlin** [PelicanPlatform/pelican#954]
Pelican Service:
- [ ] Client
- [ ] Plugin
- [X] Registry
- [X] Director
- [X] Origin
- [X] Cache
- [ ] Other (please give the detail)

**Is your feature request related to a problem? Please describe.**

In Kubernetes, we constructing different layers of generic Pelican vs OSDF services where the latter is based on the former. To provide a consistent config interface to the operator, we're having them just use `PELICAN_*` env vars. To do this, we have to do a fair amount of hackery with kustomize patching that only really works for the variables that we explicitly list in our hack:

For example, in the `osdf-origin` base, we have

```
patches:
  - path: deployment-patch.yaml
  # Vars need to be defined ahead of any references so we use a
  # JSON6902 style patch to make sure they're appended to the list
  - path: osdf-env-vars.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: pelican-origin
      labelSelector: "app=pelican-origin,federation=osdf"
```

And in `osdf-env-vars.yaml`:

```
---
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: "OSDF_FEDERATION_DISCOVERYURL"
    value: "$(PELICAN_FEDERATION_DISCOVERYURL)"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: "OSDF_SERVER_WEBPORT"
    value: "$(PELICAN_SERVER_WEBPORT)"
<snip>
```

**Describe the solution you'd like**

We could eliminate a lot of the above complexity if the `osdf` binary respected `PELICAN_*` style environment variables.
